export const productActionTypes = {
  REQUEST_GET_PRODUCTS: "REQUEST_GET_PRODUCTS",
  SUCCESS_GET_PRODUCTS: "SUCCESS_GET_PRODUCTS",
  ERROR_GET_PRODUCTS: "ERROR_GET_PRODUCTS",

  REQUEST_GET_PRODUCT_DETAILS: "REQUEST_GET_PRODUCT_DETAILS",
  SUCCESS_GET_PRODUCT_DETAILS: "SUCCESS_GET_PRODUCT_DETAILS",
  ERROR_GET_PRODUCT_DETAILS: "ERROR_GET_PRODUCT_DETAILS",

  RESET_PRODUCT_DETAILS: "RESET_PRODUCT_DETAILS",
};
